add_newline = true

format = "$all"

[username]
disabled = false
show_always = true
style_user = "bold yellow"
format = "[$user[@](bold blue)]($style)"

[hostname]
disabled = false
ssh_only = false
style = "bold white"
format =  "[$hostname]($style) "

[directory]
disabled = false
truncation_length = 1
home_symbol = "~"
format = "[in](bold purple) [$path](bold cyan)[/](bold green) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[](bold red)"

[git_branch]
symbol = " "
style = "bold blue"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[󱇯 PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"
conflicted = "= "
ahead = "⇡ ${count} "
behind = "⇣ ${count} "
diverged = "⇕ "
up_to_date = "󰄬"
untracked = "? "
stashed = "$ "
modified = "! "
staged = '[++\($count\)](green)'
renamed = "» "
deleted = " "

[cmd_duration]
disabled = true
